name: publish

on:
  release:
    types:
      - published

jobs:
  release:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set metadata
        run: |
          version="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=${version}" >> ${GITHUB_ENV}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.agent
          platforms: linux/amd64,linux/arm64
          tags: |
            snsinfu/rtun:latest
            snsinfu/rtun:${{ env.VERSION }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.server
          platforms: linux/amd64,linux/arm64
          tags: |
            snsinfu/rtun-server:latest
            snsinfu/rtun-server:${{ env.VERSION }}
          push: true
